version: "3.9"
services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
  model:
    image: 'taekkim/math_code_generate:latest'
    ports:
      - "5000:5000"
    volumes:
      - ./model/generate:/home/bentoml/bento/src